### PR TITLE
feature/Placeholder: Placeholder component v1

### PR DESCRIPTION
**Pull request by willthebrit**

### CODE REVIEW

**Comment by seesleestak** [comment]
Nice. It'd be cool to add color support at some point.

**Comment by billyxs** [comment]
FYI - I made a commit on this branch to remove the upload-box/lib folder from the repo.

**Comment by billyxs** [comment]
Thanks @willthebrit!

**Comment by willthebrit** [comment]
Yes! Added.

**Comment by seesleestak** [comment]
Woah, psychedelic!

**Pull request merged**
